---
apache_embeded_modules:
  - access_compat
  - actions
  - alias
  - allowmethods
  - asis
  - auth_basic
  - auth_digest
  - auth_form
  - authn_anon
  - authn_core
  - authn_dbd
  - authn_dbm
  - authn_file
  - authn_socache
  - authnz_fcgi
  - authnz_ldap
  - authz_core
  - authz_dbd
  - authz_dbm
  - authz_groupfile
  - authz_host
  - authz_owner
  - authz_user
  - autoindex
  - buffer
  - cache
  - cache_disk
  - cache_socache
  - cgi
  - cgid
  - charset_lite
  - data
  - dav
  - dav_fs
  - dav_lock
  - dbd
  - deflate
  - dialup
  - dir
  - dump_io
  - echo
  - env
  - event
  - expires
  - ext_filter
  - file_cache
  - filter
  - headers
  - heartbeat
  - heartmonitor
  - ident
  - include
  - info
  - itk
  - lbmethod_bybusyness
  - lbmethod_byrequests
  - lbmethod_bytraffic
  - lbmethod_heartbeat
  - ldap
  - log_debug
  - log_forensic
  - lua
  - macro
  - mime
  - mime_magic
  - mpm_event
  - mpm_prefork
  - mpm_worker
  - negotiation
  - pagespeed
  - prefork
  - proxy
  - proxy_ajp
  - proxy_balancer
  - proxy_connect
  - proxy_express
  - proxy_fcgi
  - proxy_fdpass
  - proxy_ftp
  - proxy_html
  - proxy_http
  - proxy_scgi
  - proxy_wstunnel
  - ratelimit
  - reflector
  - remoteip
  - reqtimeout
  - request
  - rewrite
  - sed
  - session
  - session_cookie
  - session_crypto
  - session_dbd
  - setenvif
  - slotmem_plain
  - slotmem_shm
  - socache_dbm
  - socache_memcache
  - socache_shmcb
  - speling
  - ssl
  - status
  - substitute
  - unique_id
  - userdir
  - usertrack
  - vhost_alias
  - worker
  - xml2enc

apache_mod_passenger:
  root         : '/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini'
  default_ruby : '/usr/bin/ruby'
