---
- name: "Remove default vhosts"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '{{apache_vhost_dir}}/default'
    - '{{apache_vhost_dir}}/default-ssl'
    - '{{apache_vhost_enable_dir}}/000-default'
  notify: reload apache

- name: clean-up default security module
  file:
    path: '{{ apache_mod_enable_dir }}/security.conf'
    state: absent
  when: "'security' not in apache_modules.keys()"

- name: "Ensure conf.d dir exist "
  file:
    path  : "{{ apache_confd_dir }}"
    state : directory
    owner: root
    group: root

- name: Ensure letsencrypt dir exist
  file:
    path  : "{{ apache_letsencrypt_dir }}"
    state : directory
    owner : root
    group : root

- name: "Ensure custom included directories exist "
  file:
    path : "{{ item.path }}"
    state: directory
    owner: "{% if item.path|match('/etc/apache2') %}root{% else %}{{ item.user|default(apache_user) }}{% endif %}"
    group: "{% if item.path|match('/etc/apache2') %}root{% else %}{{ item.user|default(apache_group) }}{% endif %}"
  with_items: "{{ apache_include }}"
  when:
    - apache_include is defined
    - apache_include|length > 0
    - item.path not in apache_embeded_include

- name: Create symlinks for load configuration (jessie bugfix)
  file:
    src  : '{{ apache_mod_dir }}/mpm_{{ item }}.load'
    dest : '{{ apache_mod_dir }}/{{ item }}.load'
    state: 'link'
    owner: root
    group: root
    mode : '{{ apache_file_mode_symlink }}'
  when: 
    - "apache_version | version_compare('2.4', '>=')"
    - "ansible_os_family == 'Debian'"
  with_items:
    - event
    - worker
    - prefork

- name: Main configuration file
  template:
    src  : main.j2
    dest : "{{ apache_conf_dir }}/{{ apache_conf_file }}"
    owner: root
    group: root
    mode : "{{ apache_file_mode }}"
  notify: reload apache

- name: MPM configuration
  template:
    src  : modules/{{ apache_mpm }}.conf.j2
    dest : "{{ apache_mod_dir }}/{{ apache_mpm }}.conf"
    owner: root
    group: root
    mode : "{{ apache_file_mode }}"
  notify : reload apache

- name: Activate MPM configuration
  file:
    src  : "{{ apache_mod_dir_relative }}/{{ apache_mpm }}.conf"
    dest : "{{ apache_mod_enable_dir }}/{{ apache_mpm }}.conf"
    state: link
    force: yes
    owner: root
    group: root
    mode : "{{ apache_file_mode_symlink }}"
  notify : reload apache

- name: Configure ports
  template:
    src     : ports.conf.j2
    dest    : "{{ apache_conf_dir }}/ports.conf"
    owner   : root
    group   : root
    mode    : "{{ apache_file_mode }}"
  notify: reload apache

- name: Configure badbot
  template:
    src     : badbot.conf.j2
    dest    : "{{ apache_confd_dir }}/badbot.conf"
    owner   : root
    group   : root
    mode    : "{{ apache_file_mode }}"
  notify: reload apache

- name: Sets security files
  template:
    src     : security.conf.j2
    dest    : "{{ apache_confd_dir }}/security.conf"
    owner   : root
    group   : root
    mode    : "{{ apache_file_mode }}"
  notify: reload apache

- name: Set letsencrypt alias
  template:
    src     : acme.conf.j2
    dest    : "{{ apache_confd_dir }}/acme.conf"
    owner   : root
    group   : root
    mode    : "{{ apache_file_mode }}"
  notify: reload apache

- name: Create Htpasswd users
  htpasswd_:
    path        : "{{ item.0.path|default(apache_conf_dir ~ '/.' ~ item.0.name ) }}"
    name        : "{{ item.1.username }}"
    password    : "{{ item.1.password }}"
    crypt_scheme: "{{ item.1.crypt|default(omit) }}"
    owner       : "{{ item.0.owner|default('root') }}"
    group       : "{{ item.0.group|default('root') }}"
    mode        : "{{ item.0.mode|default(apache_file_mode) }}"
    state       : "{{ item.0.state|default('present') }}"
  with_subelements :
    - "{{ apache_htpasswd }}"
    - users
  no_log: yes

- name: "Remove other-vhosts-access-log file"
  file:
    path  : "{{ item }}"
    state : absent
  with_items:
    - "{{ apache_conf_enable_dir }}/other-vhosts-access-log.conf"
    - "{{ apache_confd_dir }}/other-vhosts-access-log"
  notify: reload apache

- name: 'fix security.conf override'
  file:
    path: "{{ apache_conf_enable_dir }}/security.conf"
    state: absent
  notify: reload apache

- name: "Clean default /var/www/index.html"
  file:
    path="{{ apache_docroot }}/index.html"
    state=absent
