---
- name: Include OS-specific variables.
  include_vars: "{{ item }}.yml"
  with_items:
    - "{{ ansible_os_family }}"
    - "{{ ansible_distribution }}/{{ ansible_distribution_release }}"
  tags:
    - apache
    - apache_install
    - apache_modules
    - apache_config
    - apache_vhosts

- name: Include Debian
  include: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - apache
    - apache_install

- name: Include Redhat
  include: redhat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - apache
    - apache_install

- name: Get installed version of Apache.
  shell: "$(which {{ apache_daemon }}) -v"
  changed_when: false
  check_mode: no
  register: _apache_version
  tags:
    - apache
    - apache_install
    - apache_modules
    - apache_config
    - apache_vhosts

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"
  tags:
    - apache
    - apache_install
    - apache_modules
    - apache_config
    - apache_vhosts

- name: Main Configuration
  include: configure.yml
  tags:
    - apache
    - apache_config

- name: Include modules configuration
  include: module.yml
  tags:
    - apache
    - apache_modules

- name: Include Fastcgi configuration
  include: fastcgi.yml
  when:
    - apache_fastcgi is defined
    - ansible_distribution_major_version|int < 9
  tags:
    - apache
    - apache_fastcgi


- name: Include vhosts configuraton
  include: vhost.yml
  tags:
    - apache
    - apache_vhosts
