---
# Exemple de dictionnaires de données postgresql

users_postgresql:
  database:
    - name: db_glacius
      encoding: UTF-8
      lc_collate: en_US.UTF-8
      lc_ctype: en_US.UTF-8
    - name: db_jago
    - name: db_orchid
    - name: db_spinal
  user:
    - name: glacius
      password: 'C8XR6FgsK9nME'
      database: db_glacius
      priv:
        - CONNECT
        - products:SELECT
        - users:ALL
        - name: raiden
      encrypted: true
      password: 'md5d011966da94d776cf59bf6dbde240e5d'
      expires: infinity
      role_attr_flags:
        - CREATEDB
        - NOSUPERUSER
        - CREATEROLE
    - name: sabrewulf
      encrypted: true
      password: 'md5d011966da94d776cf59bf6dbde240e5d'
      database: db_glacius
      expires: "August 25 12:00:00 2016 +1"
      priv:
        - 'ALL'
        - 'creditcard:SELECT'
        - name: spinal
      encrypted: true
      password: 'md5d011966da94d776cf59bf6dbde240e5d'
      database: db_spinal
      expires: infinity
      priv:
        - 'ALL'
    - name: jago
      encrypted: true
      password: 'md5d011966da94d776cf59bf6dbde240e5d'
      expires: infinity
  priv:
      # On database "db_orchid":
      # GRANT SELECT, INSERT, UPDATE ON TABLE public.books, public.authors public.users
      # TO glacius,admin,spinal WITH GRANT OPTION
    - name: db_orchid
      priv:
        - 'SELECT,INSERT,UPDATE'
      type: table
      objs: 'books,authors,users'
      schema: public
      roles: "glacius,raiden,spinal"
      grant_option: yes

    # GRANT ALL PRIVILEGES ON DATABASE db_jago TO jago
    # Note that here "db=postgres" specifies the database to connect to, not the
    # database to grant privileges on (which is specified via the "objs" param)
    - name: postgres
      priv:
        - 'ALL'
      type: database
      objs: db_jago
      roles: jago
      grant_option: yes

    # GRANT admin, combo TO spinal, glacius WITH ADMIN OPTION
    # Note that group role memberships apply cluster-wide and therefore are not
    # restricted to database "db_glacius" here.
    - name: db_glacius
      state           : present
      type            : group
      objs            : "raiden,sabrewulf"
      roles           : "spinal,glacius"
      admin_option    : yes
