---
galaxy_info:
  author:
    - Nicolas Vogel
    - Abdoul Bah
    - Nicolas Berhe
    - Jonathan Lestrelin
  license: GPLv3
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - jessie
        - wheezy
        - squeeze
    - name: Ubuntu
      versions:
        - Trusty
        - Precise
        - Vivid
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - web
dependencies: []
