---
- name: Create MySQL database
  mysql_db:
    name              : '{{ item.name }}'
    collation         : '{{ item.collation|default(omit) }}'
    encoding          : '{{ item.encoding|default(omit) }}'
    state             : present
    login_port        : '{{ item.login_port|default(users_mysql_default.login_port) }}'
    login_host        : '{{ item.login_host|default(users_mysql_default.login_host) }}'
    login_user        : '{{ item.login_user|default(omit) }}'
    login_password    : '{{ item.login_password|default(omit) }}'
    login_unix_socket : '{{ item.login_unix_socket|default(omit) }}'
  with_items          : "{{users_mysql.database}}"
  no_log: "{{no_log|default(true)}}"
  when                : ((users_mysql.database|length > 0 and ( item.name is defined and item.name != 'mysql' and item.name != 'information_schema' and item.name != 'performance_schema') ))

- name: Manage MySQL users
  mysql_user:
    name              : '{{ item.0.name }}'
    host              : '{{ item.1|default("users_mysql_default.login_host") }}'
    encrypted         : '{{ item.0.encrypted|default(omit)}}'
    password          : '{{ item.0.password }}'
    priv              : '{{ item.0.priv|default("users_mysql_default.priv")|join("/") }}'
    append_privs      : '{{ item.0.append_privs|default("yes") }}'
    state             : '{{ item.0.state|default("present") }}'
    login_port        : '{{ item.0.login_port|default(users_mysql_default.login_port) }}'
    login_host        : '{{ item.0.login_host|default(users_mysql_default.login_host) }}'
    login_user        : '{{ item.0.login_user|default(omit) }}'
    login_password    : '{{ item.0.login_password|default(omit) }}'
    login_unix_socket : '{{ item.0.login_unix_socket|default(omit) }}'
  no_log: "{{no_log|default(true)}}"
  with_subelements :
    - "{{users_mysql.user}}"
    - host
  when: (( users_mysql.user|length > 0) and (item.0.name != 'root') and (item.1 is defined and item.1|length > 0))

