---
php_repo:
  'php_repository':
    url          : "http://ppa.launchpad.net/ondrej/php/ubuntu"
    distribution : 'trusty'
    keyserver    : "keyserver.ubuntu.com"
    section      : 'main'
    id           : 'E5267A6C'
    state        : 'present'
    pin          : 'o=ppa.launchpad.net/ondrej/php/ubuntu'
    pin_packages : '*'
    pin_priority : '{{ php_pin_priority }}'
