---
# PHP7/Jessie - Repository par default.

php_repo:
  'php_repository':
    url          : "https://packages.sury.org/php"
    distribution : '{{ ansible_lsb.codename }}'
    key          : "https://packages.sury.org/php/apt.gpg"
    section      : 'main'
    pin          : 'o=packages.sury.org'
    pin_packages : '*'
    pin_priority : '{{ php_pin_priority }}'
    state        : present
