---
# PHP5.6/Stretch
php_fpm_daemon: php5.6-fpm
php_prefix: php5.6
php_fpm_conf_dir: /etc/php/5.6/fpm
php_cli_conf_dir: /etc/php/5.6/cli

php_repo:
  'php_repository':
    url          : "https://packages.sury.org/php/"
    distribution : "{{ ansible_distribution_release }}"
    key          : "https://packages.sury.org/php/apt.gpg"
    section      : main
    state        : present
    pin          : 'o=packages.sury.org'
    pin_packages : '*'
    pin_priority : '{{ php_pin_priority }}'
